/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Bakin2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bakin2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.Wood} position={[1.231, 0, 0]} scale={6.401} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['spruce wood rough clean']} position={[1.154, -0.006, -0.152]} rotation={[0, -1.571, 0]} scale={2.471} />
    </group>
  )
}

useGLTF.preload('/Bakin2.glb')
