/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Baking3.glb -T 
Files: public/Baking3.glb [2.71MB] > C:\Users\Asus\Desktop\volet-roulant-config\Baking3-transformed.glb [156.98KB] (94%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Baking3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Wood.003']} position={[0, 0, 2.461]} scale={6.401} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['spruce wood rough clean']} position={[0.036, -0.006, 2.322]} rotation={[0, -1.571, 0]} scale={2.471} />
    </group>
  )
}

useGLTF.preload('/Baking3-transformed.glb')
