/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/volet-roulant-v20.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

it('should render the model correctly', () => {
  const { getByText } = render(<Model />);
  expect(getByText('Volet Roulant')).toBeInTheDocument();
});

useGLTF.preload('../public/volet-roulant-v20.glb')
